version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 5
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/examples/plugins/connect"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:15"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:30"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"
